/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface Cv2XkilianWlList {
    }
}
declare global {
    interface HTMLCv2XkilianWlListElement extends Components.Cv2XkilianWlList, HTMLStencilElement {
    }
    var HTMLCv2XkilianWlListElement: {
        prototype: HTMLCv2XkilianWlListElement;
        new (): HTMLCv2XkilianWlListElement;
    };
    interface HTMLElementTagNameMap {
        "cv2-xkilian-wl-list": HTMLCv2XkilianWlListElement;
    }
}
declare namespace LocalJSX {
    interface Cv2XkilianWlList {
    }
    interface IntrinsicElements {
        "cv2-xkilian-wl-list": Cv2XkilianWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "cv2-xkilian-wl-list": LocalJSX.Cv2XkilianWlList & JSXBase.HTMLAttributes<HTMLCv2XkilianWlListElement>;
        }
    }
}
